import { motion } from 'framer-motion';
import { ArrowRight, BookOpen, Check, Sparkles, Target } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { AuthLayout } from './AuthLayout';
import { Button } from '@/components/ui/button';

export default function RegisterSuccess() {
  const location = useLocation();
  const name = (location.state as { name?: string } | null)?.name ?? 'Learner';
  return <AuthLayout><div className="text-center"><motion.div initial={{ scale: 0, rotate: -45 }} animate={{ scale: 1, rotate: 0 }} transition={{ type: 'spring', stiffness: 220, damping: 15 }} className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-success text-white shadow-lg shadow-success/25"><Check className="h-10 w-10" strokeWidth={3} /></motion.div><motion.h1 initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="mt-7 text-3xl font-bold tracking-tight text-ink-900 dark:text-white">Welcome aboard, {name}!</motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }} className="mt-3 text-sm leading-6 text-ink-500 dark:text-ink-400">Your MathMaster journey starts now. Here are three great places to begin.</motion.p><div className="mt-8 space-y-3 text-left">{[[BookOpen, 'Explore topics', 'Find lessons made for your level'], [Sparkles, 'Ask your AI tutor', 'Get unstuck with step-by-step help'], [Target, 'Take a quiz', 'See what you already know']].map(([Icon, title, description], index) => { const C = Icon as React.ElementType; return <motion.div key={title as string} initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.35 + index * 0.1 }} className="flex items-center gap-4 rounded-2xl border border-ink-200 bg-white p-4 dark:border-ink-700 dark:bg-ink-800"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-900/30 dark:text-brand-400"><C className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-ink-800 dark:text-ink-100">{title as string}</p><p className="mt-0.5 text-xs text-ink-400">{description as string}</p></div><ArrowRight className="ml-auto h-4 w-4 text-ink-300" /></motion.div>; })}</div><Link to="/dashboard" className="mt-8 block"><Button variant="gradient" size="lg" className="w-full">Go to dashboard <ArrowRight className="h-4 w-4" /></Button></Link></div></AuthLayout>;
}
